# Ejercicios de Numpy
Aprendizaje Automático - Facundo A. Lucianna – CEIoT – FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [2]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [3]:
lista = [1, 2, 3, 4, 5]
a = np.array(lista)
print(a)

[1 2 3 4 5]


Ejercicio 3: Suma los siguientes dos arrays

In [5]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [7]:
print(a+b)

[[11 13 15]
 [17 19 21]]


Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [4]:
a = np.array([[4,2,2],
              [4,1,0]])

In [5]:
print(a*3.2)

[[12.8  6.4  6.4]
 [12.8  3.2  0. ]]


Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [8]:
a = np.array([x for x in range(9)])

In [18]:
print(a.shape)
a.reshape([3, -1])


(9,)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [24]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

In [25]:
aa = a.astype(int) # Tambien puedo convertir de tipo
aa.dtype

dtype('int64')

Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [28]:
identidad = np.eye(5)
identidad2 = identidad.astype(bool)
identidad2

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [29]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

In [34]:
np.concatenate([a1,a2], axis=1)#Concatenamos en direccion de las columnas

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Ejercicio 9: Cocatena de forma vertical los mismos array

In [35]:
np.concatenate([a1,a2], axis=0)#Concatenamos en direccion de las filas

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [37]:
rango_valores = np.arange(0, 101, 2)
print(rango_valores)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [39]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

In [48]:
result=np.where(a>b) # me devuelve los indices
result

(array([2, 4]),)

Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [49]:
secuencia = np.linspace(0, 100, 5)
print("Secuencia de números:", secuencia)

Secuencia de números: [  0.  25.  50.  75. 100.]


Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [52]:
matrix = np.full((2, 3), 23)
print(matrix)

[[23 23 23]
 [23 23 23]]


Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [54]:
aleatorio = np.random.rand(8, 2)
print(aleatorio)

[[0.0610592  0.34428091]
 [0.30490837 0.03926595]
 [0.91908879 0.44456978]
 [0.6767692  0.40729003]
 [0.954412   0.89738   ]
 [0.68338844 0.90046898]
 [0.85822595 0.48697831]
 [0.36421084 0.89738008]]


Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [55]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

In [63]:
print(a*b)
print("-------------------------")
r1=np.matmul(a,b)
r2=np.matmul(b,a)
print(r1)
print("-------------------------")
print(r2)

[[ 2  6 12]
 [20 30 42]
 [56 72 90]]
-------------------------
[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
-------------------------
[[ 42  51  60]
 [ 78  96 114]
 [114 141 168]]


Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [3]:
a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

In [6]:
print(np.sort(a))

[   0    1    2    2   38   82   91  199  292  299  387  923  939 1101]


In [7]:
print(np.sort(a)[::-1])

[1101  939  923  387  299  292  199   91   82   38    2    2    1    0]


----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [3]:
# Lee el archivo CSV en un array
data = np.genfromtxt('./datasets/venta_libros.csv', delimiter=',', skip_header=1)

# Separar las columnas en 3 arrays diferentes
year = data[:, 0]
month = data[:, 1]
books = data[:, 2]

print("Año:", year)
print("Mes:", month)
print("Libros:", books)

Año: [2019. 2019. 2019. 2019. 2019. 2019. 2019. 2019. 2019. 2019. 2019. 2020.
 2020. 2020. 2020. 2020. 2020. 2020. 2020. 2020. 2020. 2020. 2020. 2021.
 2021. 2021. 2021. 2021. 2021. 2021. 2021. 2021. 2021. 2021. 2021. 2022.
 2022. 2022. 2022. 2022. 2022. 2022. 2022. 2022. 2022. 2022. 2022.]
Mes: [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.  1.  2.  3.  4.  5.  6.  7.
  8.  9. 10. 11. 12.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.  1.
  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Libros: [400. 339. 389. 141. 332. 386. 307. 304. 167. 133. 151. 276.  57. 125.
  27. 222. 363.  26. 162. 383. 383. 179. 386. 432. 482. 202. 115. 420.
  87.  36. 489. 440.  83. 258. 281. 393. 227. 236. 453. 359. 252.  57.
 473. 331. 349. 212. 131.]


Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [4]:
# Obtener el valor máximo de ventas de libros
max_books = np.max(books)

# Buscar el índice del valor máximo de ventas
max_index = np.where(books == max_books)[0][0]

# Obtener el año y mes correspondiente al valor máximo de ventas
max_year = year[max_index]
max_month = month[max_index]

print("El valor máximo de ventas de libros es:", max_books)
print("Corresponde al año:", int(max_year), "y al mes:", int(max_month))

El valor máximo de ventas de libros es: 489.0
Corresponde al año: 2021 y al mes: 8


Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [5]:
# Calcular las ventas totales
total_sales = np.sum(books)

# Calcular el promedio de ventas
average_sales = np.mean(books)

# Calcular la mediana de las ventas
median_sales = np.median(books)

# Calcular el desvío estándar de las ventas
std_deviation_sales = np.std(books)

print("Ventas totales:", total_sales)
print("Promedio de ventas:", average_sales)
print("Mediana de las ventas:", median_sales)
print("Desvío estándar de las ventas:", std_deviation_sales)

Ventas totales: 12436.0
Promedio de ventas: 264.59574468085106
Mediana de las ventas: 276.0
Desvío estándar de las ventas: 136.14223781788837
